node {
    checkout scm

    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }
        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap Deploy?'
        }
        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
            sleep time: 1, unit: 'MINUTES'
        }
    }
    stage('Push to GitHub') {
        withCredentials([gitUsernamePassword(credentialsId: 'alfayeddennita-github-token', gitToolName: 'Default')]) {
            sh 'git config --global user.name "Jenkins Pipeline"'
            sh 'git config --global user.email "jenkins@localhost"'
            sh 'git push -f https://github.com/AlfayedDennita/dicoding-cicd-java-deploy.git HEAD:main'
        }
    }
}
