name: Run Java

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build and install Maven project
      run: |
        mvn clean install

    - name: Install manual libraries
      run: |
        mvn install:install-file -Dfile=lib/xyz.jar -DgroupId=com.xyz-DartifactId=xyz -Dversion=8.3.0 -Dpackaging=jar

    - name: Run Java application
      run: |
        NAME=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # VERSION=`mvn help:evaluate -Dexpression=project.version -DforceStdout`
        echo $NAME
        # echo $VERSION
        # java -jar target/${NAME}-${VERSION}.jar
